[package]
name = "oscae-chess-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
angun-chess = { git = "https://github.com/INDA24PlusPlus/angun-chess.git" }
chess-networking = { git = "https://github.com/INDA24PlusPlus/chess-networking.git" }
raylib = "5.0.2"
